$ANSIBLE_VAULT;1.1;AES256
30366262616365643865313035313139626539393330326365643934336163376336303663363262
3565356239333962663034316630323636333836306666340a363865363030356138613732336333
36666336626637626638363738643734333333313838643231653565373431323539333438343438
3330333966383333620a393732353165663863643936346563653331396365383831623835333331
39383961356663646661653463356466316434653664616539646266666664623138616132386539
62393033343330323231386664653333393563353336633164623233616432393266623937316334
66653932656435633163346130383861646665313862666361643834336231623535373262343564
61373966303434643166343564343138343962643532633434326539613737383038613263333265
31386466613837393562643434346663326338623461636662303563363562363933386335396662
34636236626232313262333764636632356162343063343262383661643739666634666138393166
64316266363861316362306136393835346665346663643062323338316132323139396562383935
37646339626262666337
