services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/disk2/data/media:/media:ro
    user: 1000:1000

  radarr:
    image: ghcr.io/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - radarr:/config
      - /mnt/disk2/data:/data
    dns:
      - 8.8.8.8

  sonarr:
    image: ghcr.io/hotio/sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - sonarr:/config
      - /mnt/disk2/data:/data
    dns:
      - 8.8.8.8

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8080/tcp,8080/udp
      - ARGS
    volumes:
      - sabnzbd:/config
      - /mnt/disk2/data/usenet:/data/usenet
    dns:
      - 8.8.8.8

volumes:
  jellyfin-cache:
  jellyfin-config:
  radarr:
  sonarr:
  sabnzbd:
